<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Restart_box_1</name>
   <tag></tag>
   <elementGuidId>680a106a-7e94-400b-9cc7-1d0a82216f77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='grid']/div/span[@style='z-index:99']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(24) > span.box</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^2$/ >> span</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>561a854d-4269-47d5-90ae-c963d17808a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box</value>
      <webElementGuid>77562b1c-4b03-44ae-9fdc-c620a5700af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grid&quot;)/div[24]/span[@class=&quot;box&quot;]</value>
      <webElementGuid>074ab40d-3832-40f0-9789-5dd6e9140a2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='grid']/div[24]/span</value>
      <webElementGuid>5c2be07b-3c49-46fd-823d-a5ee236d87d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[24]/span</value>
      <webElementGuid>28c745a0-ea1f-4ffe-85f4-fd4cc783628d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
