<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Restart_box_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19_20_21_22_23_24</name>
   <tag></tag>
   <elementGuidId>a3c6c6a2-a465-48e7-bf4c-6d4d4555f119</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='grid']/div/span[@style='z-index:76']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(25) > span.box</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^25$/ >> span</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>50e7763a-10e0-40e5-8d5f-7619b0857169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box</value>
      <webElementGuid>a68efcb6-d7aa-4a94-a035-d1e13e61b38b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grid&quot;)/div[25]/span[@class=&quot;box&quot;]</value>
      <webElementGuid>706e176d-ebb7-485d-b306-3b9fb58b7f16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='grid']/div[25]/span</value>
      <webElementGuid>e0d7eed1-2380-41b4-a2c4-f4b015088256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[25]/span</value>
      <webElementGuid>a85a0d05-96b5-41f4-b378-1b8e4a34877b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
